CREATE TABLE `inquinamento` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FILE` LONGBLOB NOT NULL,
  `LAT` FLOAT(255,2) NOT NULL,
  `LON` FLOAT(255,2) NOT NULL,
  `CITY` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));
